#!/bin/sh
#
# $OpenBSD: openfire.rc,v 1.3 2013/03/04 15:56:13 ajacoutot Exp $

OPENFIRE_HOME="/usr/local/openfire"
OPENFIRE_LIB="${OPENFIRE_HOME}/lib"

JAVACMD="$(/usr/local/bin/javaPathHelper -c openfire)"
JAVA_HOME="$(/usr/local/bin/javaPathHelper -h openfire)"

daemon="${JAVACMD}"
daemon_flags="-server -DopenfireHome=${OPENFIRE_HOME} -Dopenfire.lib.dir=${OPENFIRE_LIB} -jar ${OPENFIRE_LIB}/startup.jar"
daemon_user="_openfire"

. /etc/rc.d/rc.subr

rc_bg=YES
rc_reload=NO

rc_cmd $1
